services:
    db:
        image: mysql:9.0.1
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: user
            MYSQL_PASSWORD: user
            MYSQL_DATABASE: movie_db
        ports:
            - "3306:3306"