spring:
    datasource:
        url: jdbc:mysql://localhost:3306/movie_db
        username: user
        password: user
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
app:
    jwt:
        secret: abcdefghijklmnOPQRSTUVWXYZ


